pipeline {
 agent none
 stages {
  stage('SCM Checkout') {
   checkout scm
  }
  stage('Compile') {
   agent any
   steps {
    timeout(time: 2000, unit: 'SECONDS') {
        echo "hello"
    }
   }
  }
  stage('Sonarqube Test') {
   agent any
   steps {
    echo env.GIT_BRANCH
    script {
     if (env.GIT_BRANCH.startsWith("origin/master")) {
      timeout(time: 2000, unit: 'SECONDS') {
       echo "master"
      }
     } else {
      echo "SonarQube Analysis Skipped"
     }
    }
   }
  }
 }
}
