pipeline {
 agent none
 stages {
  stage('Compile') {
   agent any
   steps {
    timeout(time: 2000, unit: 'SECONDS') {
        echo "hello"
    }
   }
  }
  stage('Sonarqube Test') {
   agent any
   steps {
    echo env.GIT_BRANCH
   }
  }
 }
}
